name: Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run Taskfile build
        run: task build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/shellbot
          generate_release_notes: true
